/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAside: typeof import('element-plus/es')['ElAside'];
        ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
        ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
        ElButton: typeof import('element-plus/es')['ElButton'];
        ElCard: typeof import('element-plus/es')['ElCard'];
        ElCarousel: typeof import('element-plus/es')['ElCarousel'];
        ElContainer: typeof import('element-plus/es')['ElContainer'];
        ElDialog: typeof import('element-plus/es')['ElDialog'];
        ElDropdown: typeof import('element-plus/es')['ElDropdown'];
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
        ElFooter: typeof import('element-plus/es')['ElFooter'];
        ElForm: typeof import('element-plus/es')['ElForm'];
        ElFormItem: typeof import('element-plus/es')['ElFormItem'];
        ElHeader: typeof import('element-plus/es')['ElHeader'];
        ElIcon: typeof import('element-plus/es')['ElIcon'];
        ElInput: typeof import('element-plus/es')['ElInput'];
        ElLink: typeof import('element-plus/es')['ElLink'];
        ElMain: typeof import('element-plus/es')['ElMain'];
        ElMenu: typeof import('element-plus/es')['ElMenu'];
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
        ElOption: typeof import('element-plus/es')['ElOption'];
        ElPagination: typeof import('element-plus/es')['ElPagination'];
        ElPopover: typeof import('element-plus/es')['ElPopover'];
        ElSelect: typeof import('element-plus/es')['ElSelect'];
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
        ElSwitch: typeof import('element-plus/es')['ElSwitch'];
        ElTable: typeof import('element-plus/es')['ElTable'];
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn'];
        ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
        ElUpload: typeof import('element-plus/es')['ElUpload'];
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
        IEpAvatar: typeof import('~icons/ep/avatar')['default'];
        IEpBell: typeof import('~icons/ep/bell')['default'];
        IEpEditPen: typeof import('~icons/ep/edit-pen')['default'];
        IEpHouse: typeof import('~icons/ep/house')['default'];
        IEpLock: typeof import('~icons/ep/lock')['default'];
        IEpMoon: typeof import('~icons/ep/moon')['default'];
        IEpPieChart: typeof import('~icons/ep/pie-chart')['default'];
        IEpPlus: typeof import('~icons/ep/plus')['default'];
        IEpSearch: typeof import('~icons/ep/search')['default'];
        IEpStopwatch: typeof import('~icons/ep/stopwatch')['default'];
        IEpSunny: typeof import('~icons/ep/sunny')['default'];
        IEpTickets: typeof import('~icons/ep/tickets')['default'];
        IEpUpload: typeof import('~icons/ep/upload')['default'];
        IEpUser: typeof import('~icons/ep/user')['default'];
        LeftNav: typeof import('./src/components/left-nav.vue')['default'];
        RouterLink: typeof import('vue-router')['RouterLink'];
        RouterView: typeof import('vue-router')['RouterView'];
        ThemeSwitch: typeof import('./src/components/theme-switch.vue')['default'];
        TopNav: typeof import('./src/components/top-nav.vue')['default'];
    }
}
