name: release

on:
  push:
    branches: main # main 分支提交时触发

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 签出代码
        uses: actions/checkout@main
      - name: 安装 nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: 安装pnpm
        run: npm install pnpm
      - name: 安装依赖
        run: pnpm install
        working-directory: client-vue/mobile # working-directory 指定 shell 命令运行目录
      - name: 前端项目打包
        run: pnpm run build
        working-directory: client-vue/mobile
      - name: 发布腾讯云
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到腾讯云
        with:
          username: 'root'
          server: '${{ secrets.TENCENT_SERVER_HOST }}'
          ssh_private_key: '${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}'
          local_path: 'client-vue/mobile/dist/*'
          remote_path: '/www/wwwroot/www.ailan.top/'
          args: "-o ConnectTimeout=5"

